version: "3.3"
services:
  foodwallah_backend:
    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/foodwallah:backend
    container_name: foodwallah_backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foodwallah_backend.rule=Host(`api.foodwallah.com`)"
      - "traefik.http.routers.foodwallah_backend.service=foodwallah_backend"
      - "traefik.http.services.foodwallah_backend.loadbalancer.server.port=8080"
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp
networks:
  traefik_network:
    external: true

