version: "3.3"
services:
  foodwallah_cms:
    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/foodwallah:cms
    container_name: foodwallah_cms
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foodwallah_cms.rule=Host(`cms.foodwallah.com`)"
      - "traefik.http.routers.foodwallah_cms.service=foodwallah_cms"
      - "traefik.http.services.foodwallah_cms.loadbalancer.server.port=3000"
    networks:
      - traefik_network

networks:
    traefik_network:
      external: true

