version: "3.3"
services:
  foodwallah_ui:
    image: 537408061242.dkr.ecr.us-east-2.amazonaws.com/foodwallah:ui
    container_name: foodwallah_ui
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foodwallah_ui.rule=Host(`foodwallah.com`, `www.foodwallah.com`)"
      - "traefik.http.routers.foodwallah_ui.service=foodwallah_ui"
      - "traefik.http.services.foodwallah_ui.loadbalancer.server.port=3000"
    networks:
      - traefik_network

networks:
    traefik_network:
      external: true

